### ISSUE TITLE
64 or 32

### ISSUE THREAD

**Issue by ncaio** [eijah/demoncrypt#1]
hey guys, congratulation for the work. There is one small detail which we should ponder: see the screenshot. 

![demosaw](https://cloud.githubusercontent.com/assets/546884/9140663/389f1630-3d09-11e5-84ad-a8c047a43318.png)

**Comment by eijah** [comment]
I might have incorrectly named the 32 and 64 bit Linux executables. Looking into it now. Thanks!
On Aug 7, 2015 9:36 AM, "Noilson Caio T. de Araújo" <notifications@github.com> wrote:hey guys, congratulation for the work. There is one small detail which we should ponder: see the screenshot.

**Comment by ncaio** [comment]
think nothing of it.

**Comment by eijah** [comment]
Fixed. Sorry about this. I accidentally switched the 32 & 64 bit hashes.  Not enough sleep at Defcon.
